version: 2
sources:
  - name: rds
    database: northwinds
    schema: public
    tables:
      - name: customers
      - name: orders 
      - name: products
      - name: order_details
      - name: employees
